# CICD pipeline for Demo Springboot
name: SpringBoot CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4



      # - name: Run Docker version
      #   run: docker --version

      # - name: Run Docker Compose version
      #   run: docker compose --version

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Copy .env_sample to .env
        run: cp ./.env_sample ./.env

      - name: Down Docker container
        run:  docker-compose down

      - name: Build Docker containers
        run:  docker-compose up --build -d

  deploy:
    needs: build
    runs-on: [self-hosted, demodrkare]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Uncomment if deployment requires starting containers
      # - name: Start Docker containers
      #   run: sudo docker-compose up -d

      # - name: Wait for containers to initialize (optional)
      #   run: sleep 30
      
      - name: Delete old Docker container and image
        run: |
            CONTAINER_NAME="postgres-db-demosb"
            IMAGE_NAME="postgres:latest" 
            CONTAINER_NAME1="springboot-app-demosb"
            IMAGE_NAME1="demospringboot-springboot-app-demosb" 
            echo "${{ secrets.PASSWORD }}" | sudo -S docker rm -f $CONTAINER_NAME || true
            echo "${{ secrets.PASSWORD }}" | sudo -S docker rmi -f $IMAGE_NAME || true
            echo "${{ secrets.PASSWORD }}" | sudo -S docker rm -f $CONTAINER_NAME1 || true
            echo "${{ secrets.PASSWORD }}" | sudo -S docker rmi -f $IMAGE_NAME1 || true
     
      - name: Copy .env_sample to .env
        run: cp ./.env_sample /home/test_env/actions-runner-demodrkare/_work/DemoSpringboot/DemoSpringboot/.env 
      
      - name: Build Docker containers
        run: docker compose up --build -d

      - name: Check logs for Spring Boot container
        run: docker compose logs springboot-app-demosb
